### ISSUE TITLE
tag-master can't push and fails with ssh-askpass error

### ISSUE THREAD

**Issue by basrock** [egineering-llc/gitflow-helper-maven-plugin#47] opened 2016-12-13 10:32 UTC
Handling of development and release branches is working perfectly.
But when trying to build a master branch with Jenkins the plugin fails to push the tag to the git repository.
The server is configured in the global settings.xml which is used by the Jenkins setup.
The POM is setting <project.scm.id> to the ID mentioned in settings.xml

But anyway it seems, that the GIT is trying to open a password window, which fails.
Am I doing something wrong here?

Thanks for your help in advance.

```
Set build name.
New build name is 'origin/master - #21'
Parsing POMs
Established TCP socket on 49115
[workspace] $ /opt/gnu/ext/java/jdk1.8.0_74_64/bin/java -cp /home/jenkins/jenkins_m1/plugins/maven-plugin/WEB-INF/lib/maven32-agent-1.7.jar:/opt/maven3/apache-maven-3.2.1/boot/plexus-classworlds-2.5.1.jar:/opt/maven3/apache-maven-3.2.1/conf/logging jenkins.maven3.agent.Maven32Main /opt/maven3/apache-maven-3.2.1 /home/jenkins/jenkins_m1/cache/WEB-INF/lib/remoting-2.52.jar /home/jenkins/jenkins_m1/plugins/maven-plugin/WEB-INF/lib/maven32-interceptor-1.7.jar /home/jenkins/jenkins_m1/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.7.jar 49115
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /home/jenkins/jenkins_m1/jobs/hello-gitflow/workspace/pom.xml clean deploy
[INFO] Scanning for projects...
[INFO] Build Extension Resolved: ${env.GIT_BRANCH} to: origin/master
[INFO] gitflow-helper-maven-plugin: Enabling MasterPromoteExtension. GIT_BRANCH: [origin/master] matches masterBranchPattern: [origin/master]
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hello-gitflow 0.0.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gitflow-helper-maven-plugin:1.5.1:enforce-versions (default) @ hello-gitflow ---
[INFO] 
[INFO] --- gitflow-helper-maven-plugin:1.5.1:retarget-deploy (default) @ hello-gitflow ---
[INFO] Setting release artifact repository to: [releases::default::http://t1olasdv:8081/nexus/content/repositories/releases::false]
[INFO] 
[INFO] --- gitflow-helper-maven-plugin:1.5.1:set-properties (default) @ hello-gitflow ---
[INFO] Setting 0 properties...
[INFO] 
[INFO] --- gitflow-helper-maven-plugin:1.5.1:tag-master (default) @ hello-gitflow ---
[INFO] Invoking scm:tag for CI build matching branchPattern: [origin/master]
[INFO] Final Tag Name: '0.0.2'
[INFO] Executing: /bin/sh -c cd /home/jenkins/jenkins_m1/jobs/hello-gitflow/workspace && git tag -F /tmp/maven-scm-332888574.commit 0.0.2
[INFO] Working directory: /home/jenkins/jenkins_m1/jobs/hello-gitflow/workspace
[INFO] Executing: /bin/sh -c cd /home/jenkins/jenkins_m1/jobs/hello-gitflow/workspace && git push <git_server/project> refs/tags/0.0.2
[INFO] Working directory: /home/jenkins/jenkins_m1/jobs/hello-gitflow/workspace
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] 
(gnome-ssh-askpass:1542): Gtk-WARNING **: cannot open display:  
error: unable to read askpass response from '/usr/libexec/openssh/gnome-ssh-askpass'
fatal: could not read Username for '<git_server>': No such device or address

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.818 s
[INFO] Finished at: 2016-12-13T10:12:34+00:00
[INFO] Final Memory: 13M/199M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
```

**Comment by bvarner** [comment] 2016-12-21 14:38
Likely a duplicate of #43

**Closed** 2016-12-21 14:58 UTC
